### ISSUE TITLE
PulID Flux- Still Error when using Colab

### ISSUE THREAD

**Issue by Synchanx** [camenduru/PuLID-jupyter#2]
![image_2024-09-16_103151114](https://github.com/user-attachments/assets/7013b531-0880-4b16-89eb-0b04be6768a8)

Traceback (most recent call last):
  File "/content/PuLID-FLUX-hf/app.py", line 39, in <module>
    flux_generator = FluxGenerator()
  File "/content/PuLID-FLUX-hf/app.py", line 30, in __init__
    self.model, self.ae, self.t5, self.clip = get_models(
  File "/content/PuLID-FLUX-hf/app.py", line 19, in get_models
    model = load_flow_model(name, device="cpu" if offload else device)
  File "/content/PuLID-FLUX-hf/flux/util.py", line 117, in load_flow_model
    model = Flux(configs[name].params).to(torch.bfloat16)
  File "/content/PuLID-FLUX-hf/flux/model.py", line 74, in __init__
    [
  File "/content/PuLID-FLUX-hf/flux/model.py", line 75, in <listcomp>
    SingleStreamBlock(self.hidden_size, self.num_heads, mlp_ratio=params.mlp_ratio)
  File "/content/PuLID-FLUX-hf/flux/modules/layers.py", line 225, in __init__
    self.modulation = Modulation(hidden_size, double=False)
  File "/content/PuLID-FLUX-hf/flux/modules/layers.py", line 118, in __init__
    self.lin = nn.Linear(dim, self.multiplier * dim, bias=True)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/linear.py", line 98, in __init__
    self.weight = Parameter(torch.empty((out_features, in_features), **factory_kwargs))
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_device.py", line 78, in __torch_function__
    return func(*args, **kwargs)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 108.00 MiB. GPU

**Comment by camenduru** [comment]
we need A100 80GB

**Comment by camenduru** [comment]
![GXdhX1_WcAAZ6wV](https://github.com/user-attachments/assets/f3b75f54-3f47-41a1-8f96-12785c9bea27)

**Comment by Synchanx** [comment]
so, we should using runpod??

in the test i using with a100 80gb colab pro

wish we can use it on colab

**Comment by camenduru** [comment]
![image](https://github.com/user-attachments/assets/4d2e18d0-1057-43be-a673-0d3e482411b8)

**Comment by mattzipan** [comment]
if its not working then remove the callout for Colab pro from the readme. totally misguiding.
